#!/bin/sh

# Run the target-independent pieces of the Iris hardware validation plan.
# The suite is intentionally opt-in for external tools and corpora: a normal
# checkout can run the repository matrices, while a target with the Qualcomm
# app or Fluster checkout can add those layers through environment variables.

set -u

. "$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)/lib/iris-env.sh"

device=$(iris_resolve_device)
driver_path=${LIBVA_DRIVERS_PATH:-$(pwd)/build/src}
root=${IRIS_HARDWARE_SUITE_DIR:-$(iris_artifact_dir hardware-suite)}
run_matrices=${IRIS_RUN_REPO_MATRICES:-1}
allow_compliance_limit=${IRIS_ALLOW_KNOWN_COMPLIANCE_LIMIT:-1}
mkdir -p "$root"

failures=0
warns=0

pass() { printf 'PASS %s\n' "$*"; }
warn() { warns=$((warns + 1)); printf 'WARN %s\n' "$*"; }
fail() { failures=$((failures + 1)); printf 'FAIL %s\n' "$*" >&2; }

printf 'Iris hardware suite device=%s root=%s\n' "$device" "$root"

if [ ! -e "$device" ]; then
    fail "device-missing path=$device"
else
    if command -v v4l2-ctl >/dev/null 2>&1; then
        v4l2-ctl --all -d "$device" >"$root/v4l2-all.txt" 2>&1 || fail "v4l2-ctl-all"
        v4l2-ctl --list-formats-out-ext -d "$device" >"$root/v4l2-output-formats.txt" 2>&1 || fail "v4l2-ctl-formats"
        pass "v4l2-inventory"
    else
        fail "v4l2-ctl-missing"
    fi
fi

if command -v v4l2-compliance >/dev/null 2>&1 && [ -e "$device" ]; then
    set +e
    v4l2-compliance -d "$device" >"$root/v4l2-compliance.log" 2>&1
    rc=$?
    set -e
    if [ "$rc" -eq 0 ]; then
        pass "v4l2-compliance"
    else
        # The plain report omits the control id, so collect a verbose report
        # before deciding whether this is the known stateful-class check.
        if command -v v4l2-ctl >/dev/null 2>&1; then
            v4l2-compliance -v -d "$device" >"$root/v4l2-compliance-verbose.log" 2>&1 || true
        fi
        if [ "$allow_compliance_limit" = 1 ] \
            && [ "$(grep -c '^[[:space:]]*fail:' "$root/v4l2-compliance-verbose.log" 2>/dev/null || true)" -eq 1 ] \
            && grep -q 'Capture Buffers' "$root/v4l2-compliance-verbose.log" 2>/dev/null \
            && v4l2-ctl --list-ctrls -d "$device" 2>/dev/null | grep -q 'min_number_of_capture_buffers'; then
            # v4l2-compliance classifies this mem2mem decoder as stateful and
            # disagrees with the raw control inventory. Keep both reports.
            warn "v4l2-compliance-known-stateful-control rc=$rc log=$root/v4l2-compliance.log"
        else
            fail "v4l2-compliance rc=$rc log=$root/v4l2-compliance.log"
        fi
    fi
else
    warn "v4l2-compliance-skipped"
fi

if [ "$run_matrices" = 1 ]; then
    if [ -x test/iris-matrix.sh ]; then
        set +e
        LIBVA_V4L2_VIDEO_PATH="$device" LIBVA_DRIVERS_PATH="$driver_path" \
            IRIS_MATRIX_DIR="$root/matrix" ./test/iris-matrix.sh >"$root/iris-matrix.log" 2>&1
        rc=$?
        set -e
        [ "$rc" -eq 0 ] && pass "iris-matrix" || fail "iris-matrix rc=$rc log=$root/iris-matrix.log"
    else
        warn "iris-matrix-script-missing"
    fi
    if [ -x test/iris-structure-matrix.sh ]; then
        set +e
        LIBVA_V4L2_VIDEO_PATH="$device" LIBVA_DRIVERS_PATH="$driver_path" \
            IRIS_STRUCTURE_DIR="$root/structure-matrix" ./test/iris-structure-matrix.sh \
            >"$root/iris-structure-matrix.log" 2>&1
        rc=$?
        set -e
        [ "$rc" -eq 0 ] && pass "iris-structure-matrix" || fail "iris-structure-matrix rc=$rc log=$root/iris-structure-matrix.log"
    else
        warn "iris-structure-matrix-script-missing"
    fi
else
    warn "repository-matrices-disabled"
fi

# Run explicit native V4L2 pipelines against media generated by iris-matrix.
media_dir=${IRIS_MEDIA_DIR:-$root/matrix}
if command -v gst-launch-1.0 >/dev/null 2>&1 && command -v gst-inspect-1.0 >/dev/null 2>&1; then
    run_gst() {
        name=$1
        input=$2
        demux=$3
        parser=$4
        decoder=$5
        [ -f "$input" ] || return 2
        gst-inspect-1.0 "$decoder" >/dev/null 2>&1 || return 2
        gst-launch-1.0 -e filesrc location="$input" ! "$demux" ! "$parser" ! \
            "$decoder" capture-io-mode=2 output-io-mode=2 ! fakesink sync=false \
            >"$root/gst-$name.log" 2>&1
        grep -q 'Got EOS' "$root/gst-$name.log"
    }
    for spec in \
        'h264 test-h264.mp4 qtdemux h264parse v4l2h264dec' \
        'vp9 test-vp9.webm matroskademux vp9parse v4l2vp9dec' \
        'hevc test-hevc.mkv matroskademux h265parse v4l2h265dec' \
        'av1 test-av1.webm matroskademux av1parse v4l2av1dec'; do
        set -- $spec
        name=$1
        set -- $spec
        input="$media_dir/$2"
        demux=$3
        parser=$4
        decoder=$5
        set +e
        run_gst "$name" "$input" "$demux" "$parser" "$decoder"
        rc=$?
        set -e
        if [ "$rc" -eq 0 ]; then
            pass "gstreamer-$name"
        elif [ "$rc" -eq 2 ]; then
            warn "gstreamer-$name-skipped input-or-element-missing"
        else
            fail "gstreamer-$name rc=$rc log=$root/gst-$name.log"
        fi
    done
else
    warn "gstreamer-skipped"
fi

# Qualcomm's JSON test app is an optional native V4L2 oracle. Supply a
# whitespace-separated list of configs when the upstream checkout is present.
qualcomm_binary=${IRIS_V4L_TEST_BINARY:-}
qualcomm_configs=${IRIS_V4L_TEST_CONFIGS:-}
qualcomm_cwd=${IRIS_V4L_TEST_CWD:-}
if [ -n "$qualcomm_binary" ] && [ -n "$qualcomm_configs" ] && [ -x "$qualcomm_binary" ]; then
    for config in $qualcomm_configs; do
        name=$(basename "$config" .json)
        cwd=$qualcomm_cwd
        [ -n "$cwd" ] || cwd=$(dirname "$config")
        set +e
        (cd "$cwd" && "$qualcomm_binary" --config "$config") \
            >"$root/qualcomm-$name.log" 2>&1
        rc=$?
        set -e
        if [ "$rc" -eq 0 ] && grep -q 'SUCCESS!' "$root/qualcomm-$name.log"; then
            pass "qualcomm-$name"
        else
            fail "qualcomm-$name rc=$rc log=$root/qualcomm-$name.log"
        fi
    done
else
    warn "qualcomm-json-client-skipped"
fi

# Fluster is a large external corpus. Its non-zero exit status is preserved in
# the log and reported as a warning because unsupported profiles and dimensions
# are useful capability results rather than repository regressions.
#
# Which decoder Fluster drives decides what the numbers mean, and the two are
# easy to confuse. A GStreamer-*-V4L2 decoder talks to the kernel node
# directly and never loads this driver, so its results characterise the
# firmware. An FFmpeg-*-VAAPI decoder goes through libva and therefore through
# this driver, which is the only configuration that says anything about the
# code in src/. Record which one produced a given run.
fluster_dir=${FLUSTER_DIR:-}
fluster_suites=${IRIS_FLUSTER_SUITES:-}
fluster_decoders=${IRIS_FLUSTER_DECODERS:-}
if [ -n "$fluster_dir" ] && [ -n "$fluster_suites" ] && [ -n "$fluster_decoders" ] \
    && [ -f "$fluster_dir/fluster.py" ]; then
    case "$fluster_decoders" in
    *VAAPI*)
        printf 'INFO fluster runs through this driver (%s)\n' "$fluster_decoders"
        export LIBVA_DRIVER_NAME=v4l2
        export LIBVA_DRIVERS_PATH="$driver_path"
        export LIBVA_V4L2_VIDEO_PATH="$device"
        ;;
    *)
        printf 'INFO fluster bypasses this driver (%s); results describe the firmware\n' \
            "$fluster_decoders"
        ;;
    esac
    set +e
    (cd "$fluster_dir" && python3 fluster.py -r "$fluster_dir/resources" \
        -o "$root/fluster-out" run -j "${IRIS_FLUSTER_JOBS:-1}" \
        -t "${IRIS_FLUSTER_TIMEOUT:-180}" -ts $fluster_suites -d $fluster_decoders \
        -f json -so "$root/fluster.json" -q) >"$root/fluster.log" 2>&1
    rc=$?
    set -e
    [ "$rc" -eq 0 ] && pass "fluster $fluster_decoders" \
        || warn "fluster-capability-result decoders=$fluster_decoders rc=$rc log=$root/fluster.log"
else
    warn "fluster-skipped"
fi

printf 'SUMMARY failures=%s warnings=%s root=%s\n' "$failures" "$warns" "$root"
[ "$failures" -eq 0 ]
